### ISSUE TITLE
README: Show docker-compose launch method

### ISSUE THREAD

**Issue by mcandre** [1ambda/docker-kafka-connect#2]
In addition to the raw Docker commands for starting a Kafka Connect stack, could the README show how to do this with the simpler command `docker-compose up`, for those of us with Docker Toolbox installed?

**Comment by 1ambda** [comment]
@mcandre 

without kafka and ZK? currently README documented this compose file example 
- https://github.com/1ambda/docker-kafka-connect#with-docker-compose

``` yaml
version: '2'
services:
  zk:
    image: 31z4/zookeeper:3.4.8

  kafka:
    image: ches/kafka
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      ZOOKEEPER_CONNECTION_STRING: zk:2181
      ZOOKEEPER_CHROOT: /broker-0

  connect:
    image: 1ambda/kafka-connect
    links:
      - kafka
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
```
